# --- System Identity ---
HOSTNAME=""
USERNAME=""

# --- Your Installed OS Name
OS_NAME="Archlinux" # Operating System Name. Example, Archlinux

# --- Bootloader Path ---
BOOTLOADER_PATH="boot" # Where to install the EFI files. Example, /boot

# --- Kernel ---
KERNEL="linux-zen" # Kernel name. Example, linux-zen

# --- Target Disk Configuration ---
INSTALL_DISK="" # Disk containing the entire install. Example, /dev/nvme0n1
BOOT_PARTITION="" # Bootloader install, find with command: lsblk. Example, /dev/nvme0n1p1
ROOT_PARTITION="" # System install, find with command: lsblk. Example, /dev/nvme0n1p2
CHROOT_DIR="/mnt" # Where to mount the chroot system install. Example, /mnt

# --- Hardware Configuration ---
CPU=""          # options: amd, intel
GPU0=""         # options: amd, intel, nvidia, nvidia_foss
GPU1=""        # secondary GPU: amd, intel, nvidia, nvidia_foss

# --- Localization & Regional ---
MIRROR_COUNTRY="" # Two letter country name. Example, us for United States
USER_LOCALE="" # Setup locale with the following command: "cat /etc/locale.gen" Example, en_US.UTF-8 for United States
KEYMAP="" # Setup keymap with the following command: "localectl list-keymaps" Example, us for United States keyboard
TIMEZONE="" # Setup timezone with the following command: "timedatectl list-timezones" Example, timzone is America/New_York
